@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.plantuml

!includeurl https://raw.githubusercontent.com/HomeMadeBots/LCD_Interfaces/main/doc/LCD_Special_Character_Config.iuml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/LCD_Interfaces/main/doc/LCD_Commands.iuml

@enduml